### ISSUE TITLE
This package (cf binary) likley has to be GPL licensed due to linking against FFTW

### ISSUE THREAD

**Issue by moorepants** [conda-forge/xtensor-fftw-feedstock#13]
We came to the conclusion here:

conda-forge/pyshtools-feedstock#3

that the Conda Forge binaries that link against FFTW have to be GPL licensed. This would likely the case for this package too.

**Comment by egpbos** [comment]
I don't think this applies here. The package does not distribute any pre-built code, only header files, so no linking against FFTW has been done yet. Users of xtensor-fftw that do distribute built packages do have to license as GPL, since they _will_ link against FFTW. Unless of course they bought a non-free FFTW license, which is also an option :)

**Comment by egpbos** [comment]
Feel free to reopen the issue if you disagree!
